template: 'Bruker:DanmicholoBot/Kategoriovervåkning'
edit_summary: 'Oppdaterer liste over nye artikler'
host: 'no.wikipedia.org' 
mysql_host: 'nowiki-p.rrdb.toolserver.org'
mysql_db: 'nowiki_p'
maxcats: 10000 
local_db: 'catmonitor.no.db'

